// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBLqlclWvRDYyIpDWs4imaiyprzbHapGkM',
    appId: '1:1092363374390:web:cf916bd2ba1248b659ed97',
    messagingSenderId: '1092363374390',
    projectId: 'tsa-medical-app',
    authDomain: 'tsa-medical-app.firebaseapp.com',
    storageBucket: 'tsa-medical-app.appspot.com',
    measurementId: 'G-GL6LDQ5VDM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyComXQjL53MFnPUAmnWYxmifI2XZQWGFG0',
    appId: '1:1092363374390:android:8b951829b7ebd81459ed97',
    messagingSenderId: '1092363374390',
    projectId: 'tsa-medical-app',
    storageBucket: 'tsa-medical-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDBWlYTSSGBUUgtKJmy4YcHYZA9jny4vs4',
    appId: '1:1092363374390:ios:26401a43a650cbf459ed97',
    messagingSenderId: '1092363374390',
    projectId: 'tsa-medical-app',
    storageBucket: 'tsa-medical-app.appspot.com',
    iosBundleId: 'com.example.tsaMedapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDBWlYTSSGBUUgtKJmy4YcHYZA9jny4vs4',
    appId: '1:1092363374390:ios:8fa67e0d936580a359ed97',
    messagingSenderId: '1092363374390',
    projectId: 'tsa-medical-app',
    storageBucket: 'tsa-medical-app.appspot.com',
    iosBundleId: 'com.example.tsaMedapp.RunnerTests',
  );
}
